### ISSUE TITLE
How does this project handle youtube song finding and yt-dlp download limit?

### ISSUE THREAD

**Issue by j3bx** [dhruv-ahuja/spoti-dl#11]
On other similar projects it usually downloads from a match from youtube music. The most famous downloader, spotdl, has a problem which makes the program crash when surpassing the yt-dlp download limit imposed by youtube api.
I would like to know how is this implemented on this project since I don't know rust quite well and I don't seem to find where exactly is implemented.

**Comment by dhruv-ahuja** [comment]
Hey, I have not concretely tested the download limit aspect but as far as I remember downloading 5 songs in parallel was the sweet spot and was quite fast. You could try it out with maybe 7 or 8 parellel downloads but any more than would likely be throttled. I remember because downloading 10 songs took almost the same time as downloading 5 during my testing on a 100mbps connection.
I have not encountered any crashes from my end during all this time.

**Comment by j3bx** [comment]
I see, thanks
