### ISSUE TITLE
please make a yt video about this 

### ISSUE THREAD

**Issue by Darklybars** [dhruv-ahuja/spoti-dl#6]
i dont know much about python i am having alot of errors a video wud be a great of help please

**Comment by dhruv-ahuja** [comment]
Hey, what platform are you on? I have access to a Mac and can make a short video on how to setup the project there. If you are on Windows then I cannot help you out that much since I have myself had a lot of trouble setting up and configuring python environments personally.

There are several things that can go awry when installing or setting up Python which are out of scope and unrelated to the project.

**Comment by Darklybars** [comment]
thanksalot  for reaching out to me, i have found the solution for the
problem by myself after some hour of effort thanks again for the help. have
a great day
